### ISSUE TITLE
Q:Multiple button_callback

### ISSUE THREAD

**Issue by shmuelios** [MrTool/contao-multipleCallbacks#1]
Not sure I know how to implement this or if this extension solves my issue.

Quick question i'm trying to add multiple button_callback (toggles) to the operations dca like this

'operations' => array
(

    'invited' => array
    (
        'label'               => array('Invited', 'Invited'),
        'icon'                => 'visible.gif',
        'attributes'          => 'onclick="Backend.getScrollOffset();return AjaxRequest.toggleVisibility(this,%s)"',
        'button_callback'     => array('tl_fd_sign_up', 'togglePublished')
    ),

    'meets_criteria' => array
    (
        'label'               => array('Meets Criteria', 'Meets Criteria'),
        'icon'                => 'redirect.gif',
        'attributes'          => 'onclick="Backend.getScrollOffset();return AjaxRequestCycle.toggleCriteria(this,%s)"',
        'button_callback'     => array('tl_fd_sign_up', 'criteriaIcon')
    ),
...
as you may know contao only works with one button_callback (toggle) the first one! so does your extension solve this issue If so I don't know quite how to implement into the DCA.

If I need to read up on something let us know thanks.

**Comment by MrTool** [comment]
Hi schmuelios,

At first this extension is a little bit old i hope it will work with your contao version.
At second, contao use always the "last assigned" button callback, so this extension is not useful if you are trying to extend an external module with multiple callbacks, cause it could be that another module overwrites your button callback assignment.
If you wanna use it in your own module feel free.
The extension is not directly assigned in the dca array furthermore after the dca array in the way the README describe it.
In your case it could be something like this:

```php
MrTool\MultipleCallbacks\Callback::add('yourDCATableName', 'invited', array('tl_fd_sign_up', 'togglePublished'));
```

**Comment by MrTool** [comment]
it seems you had solved your issue so i close this one.
